"""empty message

Revision ID: b7817e3ad5ff
Revises: 0ce43b01163f
Create Date: 2022-04-15 17:53:51.723042

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = 'b7817e3ad5ff'
down_revision = 'fb060a24643d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('counter', sa.Column('new_field2', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('counter', 'new_field2')
    # ### end Alembic commands ###
